# Dockerfile

# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any necessary dependencies
RUN pip install -r requirements.txt

# Expose port for the API (assuming an API server is used)
EXPOSE 5000

# Run the application
CMD ["python", "ui/app.py"]
